name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout 코드
    - name: Checkout code
      uses: actions/checkout@v3

    # Node.js 설치
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # 클라이언트 빌드
    - name: Install & Build Client
      working-directory: ./client
      run: |
        npm install
        npm run build

    # 서버 설치 및 테스트
    - name: Install & Test Server
      working-directory: ./server
      run: |
        npm install
        npm test

    # 배포
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # 클라이언트 파일 배포
          rm -rf /var/www/html/*
          cp -r ./client/build/* /var/www/html/

          # 서버 배포
          pm2 stop all
          rm -rf /var/www/server/*
          cp -r ./server /var/www/server/
          cd /var/www/server/
          npm install --production
          pm2 start server.js
