name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔑 Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 🔧 Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 🐳 Configure Docker
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: 🏗 Build and Push Server Docker Image
        run: |
          cd server
          docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server/server:latest -f Dockerfile .
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server/server:latest

      - name: 🏗 Build and Push Client Docker Image
        run: |
          cd client
          docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server/client:latest -f Dockerfile .
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server/client:latest

      - name: 🚀 Deploy Server to Cloud Run
        run: |
          gcloud run deploy my-server \
            --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server/server:latest \
            --platform managed \
            --region asia-northeast3 \
            --port 3001 \
            --vpc-connector YOUR_VPC_CONNECTOR_NAME \
            --allow-unauthenticated

      - name: 🚀 Deploy Client to Cloud Run
        run: |
          gcloud run deploy my-client \
            --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server/client:latest \
            --platform managed \
            --region asia-northeast3 \
            --port 8081 \
            --allow-unauthenticated

      - name: 🔧 Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials hospital-cluster --region asia-northeast3

      - name: 🚀 Deploy MongoDB to GKE
        run: |
          cd k8s
          kubectl apply -f mongodb.yaml

      - name: 🚀 Run MongoDB Restore Job
        run: |
          cd k8s
          kubectl apply -f mongo-restore-job.yaml
          # Job 완료까지 잠시 대기 (여기서는 예시로 300초)
          sleep 300
