name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # `main` 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔑 Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 🔧 Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 🐳 Configure Docker
        run: gcloud auth configure-docker

      - name: 🏗 Build and Push Server Docker Image
        run: |
          echo "Using project ID: ${{ secrets.GCP_PROJECT_ID }}"
          if [[ -z "${{ secrets.GCP_PROJECT_ID }}" ]]; then
            echo "❌ ERROR: GCP_PROJECT_ID is empty!"
            exit 1
          fi
          cd server
          docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server -f Dockerfile .
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server

      - name: 🏗 Build and Push Client Docker Image
        run: |
          cd client
          docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-client -f Dockerfile .
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-client

      - name: 🚀 Deploy Server to Cloud Run
        run: |
          gcloud run deploy my-server \
            --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-server \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      - name: 🚀 Deploy Client to Cloud Run
        run: |
          gcloud run deploy my-client \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-client \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
